import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Footer } from "@/components/Footer";
import { Header } from "@/components/Header";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
   title: "Amazon goods",
   description: "Generated by Shoxa",
   icons: {
      icon: './logo.png'
   }
};

export default function RootLayout({
   children,
}: {
   children: React.ReactNode;
}) {
   return (
      <html lang="en">
         <head>
         <link rel="icon" href="./logo.png" sizes="any" />
         </head>
         <body>
            <Header />
            {children}
            <Footer />
         </body>
      </html>
   );
}
